src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;



/**
 * News
 *
 * @ORM\Table(name="news")
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @Vich\Uploadable
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string" , length=1024)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="news_photo", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $date_publication;

    /**
     * @ORM\Column(type="string", length=1024)
     * @var string
     */
    private $shortDescription;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @var string
     */
    private $fullDescription;



    /**
     * @var Tag
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Tag", inversedBy="news")
     */
    private $tag;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="news")
     */
    private $category;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="news")
     */
    private $user;

    /**
     * @var Comment
     *
     * @ORM\ManyToOne(targetEntity="Comment", inversedBy="news")
     */
    private $comment;


    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var integer
     */
    private $quality;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var integer
     */
    private $relevant;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var integer
     */
    private $pleasure;


    public function __construct()
    {
        $this->date = new \DateTime('now');
        $this->pleasure = 0;
        $this->quality = 0;
        $this->relevant = 0;

    }

    /**
     * @param string $title
     * @return News
     */
    public function setTitle(string $title): News
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }


    public function setImage($image)
    {
        $this->image = $image;
        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param File $imageFile
     * @return News
     */
    public function setImageFile(File $imageFile): ?News
    {
        $this->imageFile = $imageFile;
        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param \DateTime $date_create
     * @return News
     */
    public function setDate(\DateTime $date_create): News
    {
        $this->date = $date_create;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param string $shortDescription
     * @return News
     */
    public function setShortDescription(string $shortDescription): News
    {
        $this->shortDescription = $shortDescription;
        return $this;
    }

    /**
     * @return string
     */
    public function getShortDescription()
    {
        return $this->shortDescription;
    }

    /**
     * @param string $fullDescription
     * @return News
     */
    public function setFullDescription(string $fullDescription): News
    {
        $this->fullDescription = $fullDescription;
        return $this;
    }

    /**
     * @return string
     */
    public function getFullDescription()
    {
        return $this->fullDescription;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param \DateTime $date_publication
     * @return News
     */
    public function setDatePublication(\DateTime $date_publication): News
    {
        $this->date_publication = $date_publication;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDatePublication()
    {
        return $this->date_publication;
    }

    /**
     * @param Tag $tag
     * @return News
     */
    public function setTag(Tag $tag): ?News
    {
        $this->tag = $tag;
        return $this;
    }

    /**
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * @param Category $category
     * @return News
     */
    public function setCategory(Category $category): ?News
    {
        $this->category = $category;
        return $this;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param User $user
     * @return News
     */
    public function setUser(User $user): ?News
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param Comment $comment
     * @return News
     */
    public function setComment(Comment $comment): ?News
    {
        $this->comment = $comment;
        return $this;
    }

    /**
     * @return Comment
     */
    public function getComment(): Comment
    {
        return $this->comment;
    }

    /**
     * @param int $quality
     * @return News
     */
    public function setQuality(int $quality): ?News
    {
        $this->quality = $quality;
        return $this;
    }

    /**
     * @return int
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * @param int $relevant
     * @return News
     */
    public function setRelevant(int $relevant): ?News
    {
        $this->relevant = $relevant;
        return $this;
    }

    /**
     * @return int
     */
    public function getRelevant()
    {
        return $this->relevant;
    }

    /**
     * @param int $pleasure
     * @return News
     */
    public function setPleasure(int $pleasure): ?News
    {
        $this->pleasure = $pleasure;
        return $this;
    }

    /**
     * @return int
     */
    public function getPleasure()
    {
        return $this->pleasure;
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Новостная лента{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/fontawesome-all.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <a class="navbar-brand" href="">
            {% if is_granted("ROLE_USER") %}
                {{ app.user.username }}
            {% endif %}
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('homepage') }}">Главная</a>
            </li>
            {% if is_granted("ROLE_USER") %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_security_logout') }}">Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('create') }}">Добавить новость</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_registration_register') }}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_security_login') }}">Войти</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>
<div class="container pt-4">
    <div class="row">
        <div class="col mx-auto">
            {% set notices = app.flashes('notice') %}
            {% set errors = app.flashes('error') %}

            {% if notices %}
                {% for message in notices %}
                    <div class="notice">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% if errors %}

                {% for message in errors %}
                    <div class="error">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>

{% block javascripts %}
    <script src="{{ asset('vendor/jquery/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('vendor/popper/js/popper.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
{% endblock %}
</body>
</html>

templates/category.html.twig
{% extends 'base.html.twig' %}

{% block title %} Новости

{% endblock %}

{% block content %}
    <h1>Новости по категориям</h1>

    <div>
    {% for one_news in news %}
    <div class="module-page-item">
        <div class="row">
            <div class="col-md-9" style="text-align: center; border: 2px black solid">
                <p>Категория: <a
                            href="{{ path('category',{'id': one_news.category.id}) }}">{{ one_news.category.name }}</a>
                </p>
                <h4 class="module-page-name">{{ one_news.title }}</h4>
                <p style="font-size: 20px">{{ one_news.shortDescription }}</p>

                <img class="card-img-top" style="width: 400px" src="{{ vich_uploader_asset(one_news, 'imageFile') }}"/>

                <p>Автор: {{ one_news.user.fullName }} </p>
                <div class="time" style="font-size: 15px">
                    <p>Дата создания публикации:
                        {{ one_news.date|date('d') }}/
                        {{ one_news.date|date("m") }}/
                        {{ one_news.date|date('Y') }} </p>

                    <p>Дата публикации:
                        {{ one_news.datePublication|date('d') }}/
                        {{ one_news.datePublication|date("m") }}/
                        {{ one_news.datePublication|date('Y') }} </p>


                </div>

                <p style="margin-top: 20px">Теги: <a
                            href="{{ path('tag',{'id': one_news.tag.id}) }}">{{ one_news.tag.name }}</a></p><br>

                {% if is_granted("ROLE_USER") %}
                    <p>Качествено проголосовало: {{ one_news.quality }} | <a href="">+</a> | <a href=""> - </a> | <br>
                        Актуально проголосовало: {{ one_news.relevant }} | <a href="">+</a> | <a href=""> - </a> | <br>
                        Доволны: {{ one_news.pleasure }} | <a href="">+</a> | <a href=""> - </a> | <br></p>
                {% else %}
                    <p>Качествено проголосовало: {{ one_news.quality }} <br>
                        Актуально проголосовало: {{ one_news.relevant }} <br>
                        Доволны: {{ one_news.pleasure }} <br></p>

                {% endif %}


                <p style="padding-bottom: 20px;">Чтобы узнать подробнее жми <a href="{{ path('description',{'id': one_news.id}) }}">сюда</a></p>
                <hr>
                <div><h5>Комменты:</h5>

                    <p>{{ one_news.comment.description }}</p></div>

                <hr>


                <hr>
            </div>
        </div>
        {% endfor %}
    </div>


{% endblock %}

templates/create_news.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новости

{% endblock %}



{% block content %}
    <h1>Создание новости</h1>

    {{ form(form) }}

{% endblock %}

templates/full_description.html.twig
{% extends 'base.html.twig' %}

{% block title %} Новости

{% endblock %}

{% block content %}
    <h1>Полное описание новости</h1>

    <div class="module-page-item">
    <div class="row">
        <div class="col-md-9" style="text-align: center">
            <p>Категория: <a href="{{ path('category',{'id': news.category.id}) }}">{{ news.category.name }}</a></p>
            <h4 class="module-page-name">{{ news.title }}</h4>
            <p style="font-size: 20px">{{ news.shortDescription }}</p>

            <img class="card-img-top" style="width: 800px" src="{{ vich_uploader_asset(news, 'imageFile') }}"/>

            <p>Автор: {{ news.user.fullName }} </p>

            <div class="time" style="font-size: 15px">
                <p>Дата создания публикации:
                    {{ news.date|date('d') }}/
                    {{ news.date|date("m") }}/
                    {{ news.date|date('Y') }} </p>

                <p>Дата публикации:
                    {{ news.datePublication|date('d') }}/
                    {{ news.datePublication|date("m") }}/
                    {{ news.datePublication|date('Y') }} </p>


            </div>

            <p style="margin-top: 20px">Теги: <a
                        href="{{ path('tag',{'id': news.tag.id}) }}">{{ news.tag.name }}</a></p><br>

            {% if is_granted("ROLE_USER") %}
                <p>Качествено проголосовало: {{ news.quality }} | <a href="{{ path('favorite',{'id': '1'}) }}">+</a> |
                    <a href="{{ path('favorite',{'id': '4'}) }}"> - </a> | <br>
                    Актуально проголосовало: {{ news.relevant }} | <a href="{{ path('favorite',{'id': '2'}) }}">+</a> |
                    <a href="{{ path('favorite',{'id': '5'}) }}"> - </a> | <br>
                    Доволны: {{ news.pleasure }} | <a href="{{ path('favorite',{'id': '3'}) }}">+</a> | <a
                            href="{{ path('favorite',{'id': '6'}) }}"> - </a> | <br></p>
            {% else %}
                <p>Качествено проголосовало: {{ news.quality }} <br>
                    Актуально проголосовало: {{ news.relevant }} <br>
                    Доволны: {{ news.pleasure }} <br></p>

            {% endif %}

            <h5>Полное описание:</h5>
            <p>{{ news.fullDescription }}</p>

            <hr>
            <div><h5>Комменты:</h5>

                <p>{{ news.comment.description }}</p></div>

            <hr>


            <hr>
        </div>
    </div>


{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Новости

{% endblock %}

{% block content %}
    <h1>Новостная лента</h1>

    {% for one_news in news %}
    <div class="module-page-item">
        <div class="row">
            <div class="col-md-9" style="text-align: center; border: 2px black solid">
                <p>Категория: <a
                            href="{{ path('category',{'id': one_news.category.id}) }}">{{ one_news.category.name }}</a>
                </p>
                <h4 class="module-page-name">{{ one_news.title }}</h4>
                <p style="font-size: 20px">{{ one_news.shortDescription }}</p>

                <img class="card-img-top" style="width: 400px" src="{{ vich_uploader_asset(one_news, 'imageFile') }}"/>

                <p>Автор: {{ one_news.user.fullName }} </p>
                <div class="time" style="font-size: 15px">
                    <p>Дата создания публикации:
                        {{ one_news.date|date('d') }}/
                        {{ one_news.date|date("m") }}/
                        {{ one_news.date|date('Y') }} </p>

                    <p>Дата публикации:
                        {{ one_news.datePublication|date('d') }}/
                        {{ one_news.datePublication|date("m") }}/
                        {{ one_news.datePublication|date('Y') }} </p>


                </div>

                <p style="margin-top: 20px">Теги: <a
                            href="{{ path('tag',{'id': one_news.tag.id}) }}">{{ one_news.tag.name }}</a></p><br>

                {% if is_granted("ROLE_USER") %}
                    <p>Качествено проголосовало: {{ one_news.quality }} | <a href="">+</a> | <a href=""> - </a> | <br>
                        Актуально проголосовало: {{ one_news.relevant }} | <a href="">+</a> | <a href=""> - </a> | <br>
                        Доволны: {{ one_news.pleasure }} | <a href="">+</a> | <a href=""> - </a> | <br></p>
                {% else %}
                    <p>Качествено проголосовало: {{ one_news.quality }} <br>
                        Актуально проголосовало: {{ one_news.relevant }} <br>
                        Доволны: {{ one_news.pleasure }} <br></p>

                {% endif %}


                <p style="padding-bottom: 20px;">Чтобы узнать подробнее жми <a href="{{ path('description',{'id': one_news.id}) }}">сюда</a></p>
                <hr>
                <div><h5>Комменты:</h5>

                    <p>{{ one_news.comment.description }}</p></div>

                <hr>


                <hr>
            </div>
        </div>
        {% endfor %}



{% endblock %}

templates/tag.html.twig
{% extends 'base.html.twig' %}

{% block title %} Новости

{% endblock %}

{% block content %}
    <h1>Все новости по запрошенному тегу</h1>

    <div>
    {% for one_news in news %}
    <div class="module-page-item">
        <div class="row">
            <div class="col-md-9" style="text-align: center; border: 2px black solid">
                <p>Категория: <a
                            href="{{ path('category',{'id': one_news.category.id}) }}">{{ one_news.category.name }}</a>
                </p>
                <h4 class="module-page-name">{{ one_news.title }}</h4>
                <p style="font-size: 20px">{{ one_news.shortDescription }}</p>

                <img class="card-img-top" style="width: 400px" src="{{ vich_uploader_asset(one_news, 'imageFile') }}"/>

                <p>Автор: {{ one_news.user.fullName }} </p>
                <div class="time" style="font-size: 15px">
                    <p>Дата создания публикации:
                        {{ one_news.date|date('d') }}/
                        {{ one_news.date|date("m") }}/
                        {{ one_news.date|date('Y') }} </p>

                    <p>Дата публикации:
                        {{ one_news.datePublication|date('d') }}/
                        {{ one_news.datePublication|date("m") }}/
                        {{ one_news.datePublication|date('Y') }} </p>


                </div>

                <p style="margin-top: 20px">Теги: <a
                            href="{{ path('tag',{'id': one_news.tag.id}) }}">{{ one_news.tag.name }}</a></p><br>

                {% if is_granted("ROLE_USER") %}
                    <p>Качествено проголосовало: {{ one_news.quality }} | <a href="">+</a> | <a href=""> - </a> | <br>
                        Актуально проголосовало: {{ one_news.relevant }} | <a href="">+</a> | <a href=""> - </a> | <br>
                        Доволны: {{ one_news.pleasure }} | <a href="">+</a> | <a href=""> - </a> | <br></p>
                {% else %}
                    <p>Качествено проголосовало: {{ one_news.quality }} <br>
                        Актуально проголосовало: {{ one_news.relevant }} <br>
                        Доволны: {{ one_news.pleasure }} <br></p>

                {% endif %}


                <p style="padding-bottom: 20px;">Чтобы узнать подробнее жми <a href="{{ path('description',{'id': one_news.id}) }}">сюда</a></p>
                <hr>
                <div><h5>Комменты:</h5>

                    <p>{{ one_news.comment.description }}</p></div>

                <hr>


                <hr>
            </div>
        </div>
        {% endfor %}

    </div>


{% endblock %}